export class XProduct {
  id: number;
  sn: string;
  label: string;
  creator_sn: string;
  create_dt: string;
  custom_code: string;
  last_update_dt: string;
  display_code: number;
  is_deleted: number;
  is_na: number;
  class_sn: string;
  type_sn: string;
  status_sn: string;
  level_sn: string;
  class_label: string;
  type_label: string;
  level_label: string;
  status_label: string;
  more_info: string;
  seo_tag: string;
  sku: string;
  moq: string;
  price_sale: string;
  price_out: string;
  img_file_sn: string;
  enterprise_sn: string;
  project_sn: string;
  detail_info: string;
  moq_unit: string;
  creator_label: string;
  enterprise_label: string;
  project_label: string;
  scenes: string;
  industries: string;
  favor_user_label: string;
  attachedfile:string;
  coop_status:string;
  sample_provided:string;
}
